#!/bin/bash

export UEFI_NUMBER=1
export BOOT_NUMBER=2
export SWAP_NUMBER=3
export ROOT_NUMBER=4

export UEFI_SIZE="1G"
export BOOT_SIZE="4G"
export SWAP_SIZE="8G"

export UEFI_MOUNT="/boot/efi"
export BOOT_MOUNT="/boot/"
export ROOT_MOUNT="/"


